import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedInputStream;
import java.io.FileInputStream;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;
import javazoom.jl.decoder.JavaLayerException;
import javazoom.jl.player.Player;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Dell
 */
public class BeatsFrame extends javax.swing.JFrame {
 private JButton playButton, pauseButton, resumeButton, nextButton, previousButton;
    private JLabel currentlyPlayingLabel;
    private List<String> filenames;
    private int currentIndex;
    private Player player;
    private boolean isPlaying;

    /**
     * Creates new form BeatsFrame
     */
    public BeatsFrame(List<String> filenames) {
       this.filenames = filenames;
        this.currentIndex = 0;
        initComponents();
        setTitle("Music Player");
        //setSize(800, 400);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLayout(null);
        ImageIcon icon = new ImageIcon("music_icon.png");
        setIconImage(icon.getImage());

        playButton = new JButton("Play");
        pauseButton = new JButton("Pause");
        resumeButton = new JButton("Resume");
        nextButton = new JButton("Next");
        previousButton = new JButton("Previous");

        //currentlyPlayingLabel = new JLabel("Currently Playing: ");

        playButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                playActionPerformed(evt);
            }
        });
        pauseButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                pauseActionPerformed(evt);
            }
        });
        resumeButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                ResumeActionPerformed(evt);
            }
        });
        nextButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        previousButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                previousActionPerformed(evt);
            }
        });

      

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        pause = new javax.swing.JButton();
        previous = new javax.swing.JButton();
        play = new javax.swing.JButton();
        next = new javax.swing.JButton();
        Resume = new javax.swing.JButton();
        MusicName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img5.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setPreferredSize(new java.awt.Dimension(500, 500));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 300, 260));

        pause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pause.jpg"))); // NOI18N
        pause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseActionPerformed(evt);
            }
        });
        getContentPane().add(pause, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 62, -1));

        previous.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WhatsApp Image 2024-04-22 at 15.29.20_adbb1c9f.jpg"))); // NOI18N
        previous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousActionPerformed(evt);
            }
        });
        getContentPane().add(previous, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 60, -1));

        play.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paly.jpg"))); // NOI18N
        play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playActionPerformed(evt);
            }
        });
        getContentPane().add(play, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 61, -1));

        next.setForeground(new java.awt.Color(0, 51, 255));
        next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/next.jpg"))); // NOI18N
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        getContentPane().add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, 60, -1));

        Resume.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stop.jpg"))); // NOI18N
        Resume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResumeActionPerformed(evt);
            }
        });
        getContentPane().add(Resume, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 390, 60, -1));

        MusicName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        MusicName.setText("Music Name");
        MusicName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MusicNameActionPerformed(evt);
            }
        });
        getContentPane().add(MusicName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 430, 20));

        jLabel3.setBackground(new java.awt.Color(0, 102, 153));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/3update.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-300, -240, 1000, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    private void previousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousActionPerformed
      if (isPlaying) {
            stop();
        }
        currentIndex--;
        if (currentIndex < 0) {
            currentIndex = filenames.size() - 1;
        }
        play();

    }//GEN-LAST:event_previousActionPerformed

    private void playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playActionPerformed
     play();
    }//GEN-LAST:event_playActionPerformed

    private void pauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseActionPerformed
      pause();
    }//GEN-LAST:event_pauseActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
 if (isPlaying) {
            stop();
        }
        playNext();

    }//GEN-LAST:event_nextActionPerformed

    private void ResumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResumeActionPerformed
          resume();

    }//GEN-LAST:event_ResumeActionPerformed

    private void MusicNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MusicNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MusicNameActionPerformed
 private void resume() {
        if (!isPlaying) {
            play();
}
}
    private void play() {
    stop();
    new Thread(() -> {
        try {
            BufferedInputStream buffer = new BufferedInputStream(new FileInputStream(filenames.get(currentIndex)));
            player = new Player(buffer);
            player.play();
            isPlaying = true;
            SwingUtilities.invokeLater(() -> MusicName.setText(filenames.get(currentIndex)));
        } catch (Exception e) {
            System.out.println("Error playing MP3: " + e);
        }
    }).start();
}
private void stop() {
        if (player != null) {
            player.close();
            isPlaying = false;
        }
    }
private void pause() {
        if (player != null) {
            try {
                //int currentPosition = player.getPosition();
                player.close();
                isPlaying = false;
                //currentIndex = currentPosition;
            } catch (Exception e) {
                System.out.println("Error pausing MP3: " + e);
            }
        }
    }
private void playNext() {
    if(isPlaying){
        stop();
    }
    if (currentIndex < filenames.size() - 1) {
        currentIndex++;
        play();
        
    } else {
        System.out.println("No more songs to play.");
        currentIndex = 0; // Reset to the first song
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       List<String> songs = new ArrayList<>();
       
        songs.add("C:\\Users\\Dell\\Downloads\\roop tera.mp3");
        songs.add("C:\\Users\\Dell\\Downloads\\one direction.mp3");
        songs.add("C:\\Users\\Dell\\Downloads\\give me some sunshine.mp3");
        songs.add("C:\\Users\\Dell\\Downloads\\uthe kadam.mp3");
        songs.add("C:\\Users\\Dell\\Downloads\\life goe on.mp3");
        songs.add("C:\\Users\\Dell\\Downloads\\all is well.mp3");
        songs.add("C:\\Users\\Dell\\Downloads\\tadow.unknown");
        songs.add("C:\\Users\\Dell\\Downloads\\Auld Lang Syne (Instrumental) - Jingle Punks.mp3");
       
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BeatsFrame(songs).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField MusicName;
    private javax.swing.JButton Resume;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JButton next;
    private javax.swing.JButton pause;
    private javax.swing.JButton play;
    private javax.swing.JButton previous;
    // End of variables declaration//GEN-END:variables
}


